# -*- coding: utf-8 -*-
"""science tutor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117sLYkfoniG4GCbjyQkRcUP2He-RwWO6
"""

pip install openai gradio

from openai import OpenAI
import gradio as gr

OPENAI_API_KEY = "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"
client = OpenAI(api_key=OPENAI_API_KEY)

system_prompt = """
You are a friendly, knowledgeable, and patient science tutor.
You help O/A Level students understand science concepts (physics, chemistry, biology, general science) in a clear and simple way.
You avoid giving direct answers unless asked. You explain concepts step-by-step using easy language, examples, and analogies when needed.
Encourage students and ask follow-up questions to guide their learning.
"""

def science_tutor_chat(user_input):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_input}
        ]
    )
    return response.choices[0].message.content

interface = gr.Interface(
    fn=science_tutor_chat,
    inputs=gr.Textbox(lines=3, placeholder="Ask your science question here...", label="Your Question"),
    outputs=gr.Textbox(label="Science Tutor's Answer"),
    title="🧪 Science Tutor Chatbot",
    description="Ask me about physics, biology, chemistry, or general science!"
)

interface.launch()

"""# Activity 2: Choose a chatbot role"""

